### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by supmyhava** [sizifart/MuskEmpireBot#1]
C:\Users\Administrator\Desktop\MuskEmpireBot-main>pnpm start

> fuflomaskempire@0.0.0 start C:\Users\Administrator\Desktop\MuskEmpireBot-main
> tsc && tsc-alias && dotenv node ./dist/index.js

√
███████╗██╗███████╗     ██████╗ ██████╗ ██████╗ ███████╗██████╗
██╔════╝██║╚══███╔╝    ██╔════╝██╔═══██╗██╔══██╗██╔════╝██╔══██╗
███████╗██║  ███╔╝     ██║     ██║   ██║██║  ██║█████╗  ██████╔╝
╚════██║██║ ███╔╝      ██║     ██║   ██║██║  ██║██╔══╝  ██╔══██╗
███████║██║███████╗    ╚██████╗╚██████╔╝██████╔╝███████╗██║  ██║
╚══════╝╚═╝╚══════╝     ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝

🤖 MuskEmpire AUTO BOT
😎 Prepared and Developed by: F.Davoodi

📝 Run a bot?
 · add
√ 📝 What do you want to call this profile? · 6c9a49c6-dc2a-40a4-86ad-3c9005b57909
√ 🧾 Choose an authorisation method · phone
√ 🔗 Do I need a proxy to connect? (y/N) · false
? 📞 Enter your phone number » C:\Users\Administrator\Desktop\MuskEmpireBot-main\node_modules\.pnpm\better-sqlite3@9.5.0\node_modules\better-sqlite3\lib\database.js:65
                throw new TypeError('Cannot open database because the directory does not exist');
                      ^

TypeError: Cannot open database because the directory does not exist
    at new Database (C:\Users\Administrator\Desktop\MuskEmpireBot-main\node_modules\.pnpm\better-sqlite3@9.5.0\node_modules\better-sqlite3\lib\database.js:65:9)
    at Database (C:\Users\Administrator\Desktop\MuskEmpireBot-main\node_modules\.pnpm\better-sqlite3@9.5.0\node_modules\better-sqlite3\lib\database.js:11:10)
    at SqliteStorageDriver._createDatabase (file:///C:/Users/Administrator/Desktop/MuskEmpireBot-main/node_modules/.pnpm/@mtcute+node@0.13.0/node_modules/@mtcute/node/esm/sqlite/driver.js:12:20)
    at SqliteStorageDriver._load (file:///C:/Users/Administrator/Desktop/MuskEmpireBot-main/node_modules/.pnpm/@mtcute+core@0.13.3/node_modules/@mtcute/core/esm/storage/sqlite/driver.js:90:24)
    at SqliteStorageDriver.load (file:///C:/Users/Administrator/Desktop/MuskEmpireBot-main/node_modules/.pnpm/@mtcute+core@0.13.3/node_modules/@mtcute/core/esm/storage/driver.js:17:24)
    at file:///C:/Users/Administrator/Desktop/MuskEmpireBot-main/node_modules/.pnpm/@mtcute+core@0.13.3/node_modules/@mtcute/core/esm/storage/storage.js:37:33
    at Object.run (file:///C:/Users/Administrator/Desktop/MuskEmpireBot-main/node_modules/.pnpm/@mtcute+core@0.13.3/node_modules/@mtcute/core/esm/utils/function-utils.js:43:26)
    at StorageManager.load (file:///C:/Users/Administrator/Desktop/MuskEmpireBot-main/node_modules/.pnpm/@mtcute+core@0.13.3/node_modules/@mtcute/core/esm/storage/storage.js:40:27)
    at file:///C:/Users/Administrator/Desktop/MuskEmpireBot-main/node_modules/.pnpm/@mtcute+core@0.13.3/node_modules/@mtcute/core/esm/network/client.js:109:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.16.0
 ELIFECYCLE  Command failed with exit code 1.
 
 C:\Users\Administrator\Desktop\MuskEmpireBot-main\node_modules\.pnpm\better-sqlite3@9.5.0\node_modules\better-sqlite3\lib\database.js:65
 
 this folder is exists

**Comment by doubleTroub1e** [comment]
try docker setup, this should solve any issues for you
